Return expected Value for Symfony Commands
This fixes a bug when calling allfeeds by hand about not returning anything which makes the generated json unuusuable with errors appended to stdout.

TypeError: Return value of "OCA\News\Command\Updater\AllFeeds::execute()" must be of the type int, "null" returned. in apps/mail/vendor/symfony/console/Command/Command.php:261

Returning "no error/0" fixes it.